TITLE Mod file for component: Component(id=NaV type=ionChannelKS)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    SUFFIX NaV
    USEION na WRITE ina VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE n_instances                       : parameter
    
    RANGE n_rateScale                       : exposure
    
    RANGE n_fcond                           : exposure
    
    RANGE n_q                               : exposure
    RANGE n_C1_relativeConductance          : parameter
    
    RANGE n_C1_q                            : exposure
    RANGE n_C2_relativeConductance          : parameter
    
    RANGE n_C2_q                            : exposure
    RANGE n_C3_relativeConductance          : parameter
    
    RANGE n_C3_q                            : exposure
    RANGE n_C4_relativeConductance          : parameter
    
    RANGE n_C4_q                            : exposure
    RANGE n_C5_relativeConductance          : parameter
    
    RANGE n_C5_q                            : exposure
    RANGE n_I1_relativeConductance          : parameter
    
    RANGE n_I1_q                            : exposure
    RANGE n_I2_relativeConductance          : parameter
    
    RANGE n_I2_q                            : exposure
    RANGE n_I3_relativeConductance          : parameter
    
    RANGE n_I3_q                            : exposure
    RANGE n_I4_relativeConductance          : parameter
    
    RANGE n_I4_q                            : exposure
    RANGE n_I5_relativeConductance          : parameter
    
    RANGE n_I5_q                            : exposure
    RANGE n_I6_relativeConductance          : parameter
    
    RANGE n_I6_q                            : exposure
    RANGE n_O_relativeConductance           : parameter
    
    RANGE n_O_q                             : exposure
    RANGE n_f01_SEC                         : parameter
    
    RANGE n_f01_rf                          : exposure
    
    RANGE n_f01_rr                          : exposure
    RANGE n_f01_rate_forward_n              : parameter
    RANGE n_f01_rate_backward_n             : parameter
    RANGE n_f01_rate_alfac                  : parameter
    RANGE n_f01_rate_btfac                  : parameter
    RANGE n_f01_rate_alpha                  : parameter
    RANGE n_f01_rate_beta                   : parameter
    RANGE n_f01_rate_x1                     : parameter
    RANGE n_f01_rate_x2                     : parameter
    RANGE n_f01_rate_base_q10               : parameter
    RANGE n_f01_rate_TENDEGREES             : parameter
    
    RANGE n_f01_rate_r                      : exposure
    RANGE n_b01_SEC                         : parameter
    
    RANGE n_b01_rf                          : exposure
    
    RANGE n_b01_rr                          : exposure
    RANGE n_b01_rate_forward_n              : parameter
    RANGE n_b01_rate_backward_n             : parameter
    RANGE n_b01_rate_alfac                  : parameter
    RANGE n_b01_rate_btfac                  : parameter
    RANGE n_b01_rate_alpha                  : parameter
    RANGE n_b01_rate_beta                   : parameter
    RANGE n_b01_rate_x1                     : parameter
    RANGE n_b01_rate_x2                     : parameter
    RANGE n_b01_rate_base_q10               : parameter
    RANGE n_b01_rate_TENDEGREES             : parameter
    
    RANGE n_b01_rate_r                      : exposure
    RANGE n_f02_SEC                         : parameter
    
    RANGE n_f02_rf                          : exposure
    
    RANGE n_f02_rr                          : exposure
    RANGE n_f02_rate_forward_n              : parameter
    RANGE n_f02_rate_backward_n             : parameter
    RANGE n_f02_rate_alfac                  : parameter
    RANGE n_f02_rate_btfac                  : parameter
    RANGE n_f02_rate_alpha                  : parameter
    RANGE n_f02_rate_beta                   : parameter
    RANGE n_f02_rate_x1                     : parameter
    RANGE n_f02_rate_x2                     : parameter
    RANGE n_f02_rate_base_q10               : parameter
    RANGE n_f02_rate_TENDEGREES             : parameter
    
    RANGE n_f02_rate_r                      : exposure
    RANGE n_b02_SEC                         : parameter
    
    RANGE n_b02_rf                          : exposure
    
    RANGE n_b02_rr                          : exposure
    RANGE n_b02_rate_forward_n              : parameter
    RANGE n_b02_rate_backward_n             : parameter
    RANGE n_b02_rate_alfac                  : parameter
    RANGE n_b02_rate_btfac                  : parameter
    RANGE n_b02_rate_alpha                  : parameter
    RANGE n_b02_rate_beta                   : parameter
    RANGE n_b02_rate_x1                     : parameter
    RANGE n_b02_rate_x2                     : parameter
    RANGE n_b02_rate_base_q10               : parameter
    RANGE n_b02_rate_TENDEGREES             : parameter
    
    RANGE n_b02_rate_r                      : exposure
    RANGE n_f03_SEC                         : parameter
    
    RANGE n_f03_rf                          : exposure
    
    RANGE n_f03_rr                          : exposure
    RANGE n_f03_rate_forward_n              : parameter
    RANGE n_f03_rate_backward_n             : parameter
    RANGE n_f03_rate_alfac                  : parameter
    RANGE n_f03_rate_btfac                  : parameter
    RANGE n_f03_rate_alpha                  : parameter
    RANGE n_f03_rate_beta                   : parameter
    RANGE n_f03_rate_x1                     : parameter
    RANGE n_f03_rate_x2                     : parameter
    RANGE n_f03_rate_base_q10               : parameter
    RANGE n_f03_rate_TENDEGREES             : parameter
    
    RANGE n_f03_rate_r                      : exposure
    RANGE n_b03_SEC                         : parameter
    
    RANGE n_b03_rf                          : exposure
    
    RANGE n_b03_rr                          : exposure
    RANGE n_b03_rate_forward_n              : parameter
    RANGE n_b03_rate_backward_n             : parameter
    RANGE n_b03_rate_alfac                  : parameter
    RANGE n_b03_rate_btfac                  : parameter
    RANGE n_b03_rate_alpha                  : parameter
    RANGE n_b03_rate_beta                   : parameter
    RANGE n_b03_rate_x1                     : parameter
    RANGE n_b03_rate_x2                     : parameter
    RANGE n_b03_rate_base_q10               : parameter
    RANGE n_b03_rate_TENDEGREES             : parameter
    
    RANGE n_b03_rate_r                      : exposure
    RANGE n_f04_SEC                         : parameter
    
    RANGE n_f04_rf                          : exposure
    
    RANGE n_f04_rr                          : exposure
    RANGE n_f04_rate_forward_n              : parameter
    RANGE n_f04_rate_backward_n             : parameter
    RANGE n_f04_rate_alfac                  : parameter
    RANGE n_f04_rate_btfac                  : parameter
    RANGE n_f04_rate_alpha                  : parameter
    RANGE n_f04_rate_beta                   : parameter
    RANGE n_f04_rate_x1                     : parameter
    RANGE n_f04_rate_x2                     : parameter
    RANGE n_f04_rate_base_q10               : parameter
    RANGE n_f04_rate_TENDEGREES             : parameter
    
    RANGE n_f04_rate_r                      : exposure
    RANGE n_b04_SEC                         : parameter
    
    RANGE n_b04_rf                          : exposure
    
    RANGE n_b04_rr                          : exposure
    RANGE n_b04_rate_forward_n              : parameter
    RANGE n_b04_rate_backward_n             : parameter
    RANGE n_b04_rate_alfac                  : parameter
    RANGE n_b04_rate_btfac                  : parameter
    RANGE n_b04_rate_alpha                  : parameter
    RANGE n_b04_rate_beta                   : parameter
    RANGE n_b04_rate_x1                     : parameter
    RANGE n_b04_rate_x2                     : parameter
    RANGE n_b04_rate_base_q10               : parameter
    RANGE n_b04_rate_TENDEGREES             : parameter
    
    RANGE n_b04_rate_r                      : exposure
    RANGE n_f00_SEC                         : parameter
    
    RANGE n_f00_rf                          : exposure
    
    RANGE n_f00_rr                          : exposure
    RANGE n_f00_rate_rate                   : parameter
    RANGE n_f00_rate_factor                 : parameter
    RANGE n_f00_rate_power                  : parameter
    RANGE n_f00_rate_base_q10               : parameter
    RANGE n_f00_rate_TENDEGREES             : parameter
    
    RANGE n_f00_rate_r                      : exposure
    RANGE n_b00_SEC                         : parameter
    
    RANGE n_b00_rf                          : exposure
    
    RANGE n_b00_rr                          : exposure
    RANGE n_b00_rate_rate                   : parameter
    RANGE n_b00_rate_factor                 : parameter
    RANGE n_b00_rate_power                  : parameter
    RANGE n_b00_rate_base_q10               : parameter
    RANGE n_b00_rate_TENDEGREES             : parameter
    
    RANGE n_b00_rate_r                      : exposure
    RANGE n_fin_SEC                         : parameter
    
    RANGE n_fin_rf                          : exposure
    
    RANGE n_fin_rr                          : exposure
    RANGE n_fin_rate_rate                   : parameter
    RANGE n_fin_rate_factor                 : parameter
    RANGE n_fin_rate_power                  : parameter
    RANGE n_fin_rate_base_q10               : parameter
    RANGE n_fin_rate_TENDEGREES             : parameter
    
    RANGE n_fin_rate_r                      : exposure
    RANGE n_bin_SEC                         : parameter
    
    RANGE n_bin_rf                          : exposure
    
    RANGE n_bin_rr                          : exposure
    RANGE n_bin_rate_rate                   : parameter
    RANGE n_bin_rate_factor                 : parameter
    RANGE n_bin_rate_power                  : parameter
    RANGE n_bin_rate_base_q10               : parameter
    RANGE n_bin_rate_TENDEGREES             : parameter
    
    RANGE n_bin_rate_r                      : exposure
    RANGE n_f11_SEC                         : parameter
    
    RANGE n_f11_rf                          : exposure
    
    RANGE n_f11_rr                          : exposure
    RANGE n_f11_rate_forward_n              : parameter
    RANGE n_f11_rate_backward_n             : parameter
    RANGE n_f11_rate_alfac                  : parameter
    RANGE n_f11_rate_btfac                  : parameter
    RANGE n_f11_rate_alpha                  : parameter
    RANGE n_f11_rate_beta                   : parameter
    RANGE n_f11_rate_x1                     : parameter
    RANGE n_f11_rate_x2                     : parameter
    RANGE n_f11_rate_base_q10               : parameter
    RANGE n_f11_rate_TENDEGREES             : parameter
    
    RANGE n_f11_rate_r                      : exposure
    RANGE n_b11_SEC                         : parameter
    
    RANGE n_b11_rf                          : exposure
    
    RANGE n_b11_rr                          : exposure
    RANGE n_b11_rate_forward_n              : parameter
    RANGE n_b11_rate_backward_n             : parameter
    RANGE n_b11_rate_alfac                  : parameter
    RANGE n_b11_rate_btfac                  : parameter
    RANGE n_b11_rate_alpha                  : parameter
    RANGE n_b11_rate_beta                   : parameter
    RANGE n_b11_rate_x1                     : parameter
    RANGE n_b11_rate_x2                     : parameter
    RANGE n_b11_rate_base_q10               : parameter
    RANGE n_b11_rate_TENDEGREES             : parameter
    
    RANGE n_b11_rate_r                      : exposure
    RANGE n_f12_SEC                         : parameter
    
    RANGE n_f12_rf                          : exposure
    
    RANGE n_f12_rr                          : exposure
    RANGE n_f12_rate_forward_n              : parameter
    RANGE n_f12_rate_backward_n             : parameter
    RANGE n_f12_rate_alfac                  : parameter
    RANGE n_f12_rate_btfac                  : parameter
    RANGE n_f12_rate_alpha                  : parameter
    RANGE n_f12_rate_beta                   : parameter
    RANGE n_f12_rate_x1                     : parameter
    RANGE n_f12_rate_x2                     : parameter
    RANGE n_f12_rate_base_q10               : parameter
    RANGE n_f12_rate_TENDEGREES             : parameter
    
    RANGE n_f12_rate_r                      : exposure
    RANGE n_b12_SEC                         : parameter
    
    RANGE n_b12_rf                          : exposure
    
    RANGE n_b12_rr                          : exposure
    RANGE n_b12_rate_forward_n              : parameter
    RANGE n_b12_rate_backward_n             : parameter
    RANGE n_b12_rate_alfac                  : parameter
    RANGE n_b12_rate_btfac                  : parameter
    RANGE n_b12_rate_alpha                  : parameter
    RANGE n_b12_rate_beta                   : parameter
    RANGE n_b12_rate_x1                     : parameter
    RANGE n_b12_rate_x2                     : parameter
    RANGE n_b12_rate_base_q10               : parameter
    RANGE n_b12_rate_TENDEGREES             : parameter
    
    RANGE n_b12_rate_r                      : exposure
    RANGE n_f13_SEC                         : parameter
    
    RANGE n_f13_rf                          : exposure
    
    RANGE n_f13_rr                          : exposure
    RANGE n_f13_rate_forward_n              : parameter
    RANGE n_f13_rate_backward_n             : parameter
    RANGE n_f13_rate_alfac                  : parameter
    RANGE n_f13_rate_btfac                  : parameter
    RANGE n_f13_rate_alpha                  : parameter
    RANGE n_f13_rate_beta                   : parameter
    RANGE n_f13_rate_x1                     : parameter
    RANGE n_f13_rate_x2                     : parameter
    RANGE n_f13_rate_base_q10               : parameter
    RANGE n_f13_rate_TENDEGREES             : parameter
    
    RANGE n_f13_rate_r                      : exposure
    RANGE n_b13_SEC                         : parameter
    
    RANGE n_b13_rf                          : exposure
    
    RANGE n_b13_rr                          : exposure
    RANGE n_b13_rate_forward_n              : parameter
    RANGE n_b13_rate_backward_n             : parameter
    RANGE n_b13_rate_alfac                  : parameter
    RANGE n_b13_rate_btfac                  : parameter
    RANGE n_b13_rate_alpha                  : parameter
    RANGE n_b13_rate_beta                   : parameter
    RANGE n_b13_rate_x1                     : parameter
    RANGE n_b13_rate_x2                     : parameter
    RANGE n_b13_rate_base_q10               : parameter
    RANGE n_b13_rate_TENDEGREES             : parameter
    
    RANGE n_b13_rate_r                      : exposure
    RANGE n_f14_SEC                         : parameter
    
    RANGE n_f14_rf                          : exposure
    
    RANGE n_f14_rr                          : exposure
    RANGE n_f14_rate_forward_n              : parameter
    RANGE n_f14_rate_backward_n             : parameter
    RANGE n_f14_rate_alfac                  : parameter
    RANGE n_f14_rate_btfac                  : parameter
    RANGE n_f14_rate_alpha                  : parameter
    RANGE n_f14_rate_beta                   : parameter
    RANGE n_f14_rate_x1                     : parameter
    RANGE n_f14_rate_x2                     : parameter
    RANGE n_f14_rate_base_q10               : parameter
    RANGE n_f14_rate_TENDEGREES             : parameter
    
    RANGE n_f14_rate_r                      : exposure
    RANGE n_b14_SEC                         : parameter
    
    RANGE n_b14_rf                          : exposure
    
    RANGE n_b14_rr                          : exposure
    RANGE n_b14_rate_forward_n              : parameter
    RANGE n_b14_rate_backward_n             : parameter
    RANGE n_b14_rate_alfac                  : parameter
    RANGE n_b14_rate_btfac                  : parameter
    RANGE n_b14_rate_alpha                  : parameter
    RANGE n_b14_rate_beta                   : parameter
    RANGE n_b14_rate_x1                     : parameter
    RANGE n_b14_rate_x2                     : parameter
    RANGE n_b14_rate_base_q10               : parameter
    RANGE n_b14_rate_TENDEGREES             : parameter
    
    RANGE n_b14_rate_r                      : exposure
    RANGE n_f1n_SEC                         : parameter
    
    RANGE n_f1n_rf                          : exposure
    
    RANGE n_f1n_rr                          : exposure
    RANGE n_f1n_rate_rate                   : parameter
    RANGE n_f1n_rate_factor                 : parameter
    RANGE n_f1n_rate_power                  : parameter
    RANGE n_f1n_rate_base_q10               : parameter
    RANGE n_f1n_rate_TENDEGREES             : parameter
    
    RANGE n_f1n_rate_r                      : exposure
    RANGE n_b1n_SEC                         : parameter
    
    RANGE n_b1n_rf                          : exposure
    
    RANGE n_b1n_rr                          : exposure
    RANGE n_b1n_rate_rate                   : parameter
    RANGE n_b1n_rate_factor                 : parameter
    RANGE n_b1n_rate_power                  : parameter
    RANGE n_b1n_rate_base_q10               : parameter
    RANGE n_b1n_rate_TENDEGREES             : parameter
    
    RANGE n_b1n_rate_r                      : exposure
    RANGE n_fi1_SEC                         : parameter
    
    RANGE n_fi1_rf                          : exposure
    
    RANGE n_fi1_rr                          : exposure
    RANGE n_fi1_rate_rate                   : parameter
    RANGE n_fi1_rate_factor                 : parameter
    RANGE n_fi1_rate_power                  : parameter
    RANGE n_fi1_rate_base_q10               : parameter
    RANGE n_fi1_rate_TENDEGREES             : parameter
    
    RANGE n_fi1_rate_r                      : exposure
    RANGE n_bi1_SEC                         : parameter
    
    RANGE n_bi1_rf                          : exposure
    
    RANGE n_bi1_rr                          : exposure
    RANGE n_bi1_rate_rate                   : parameter
    RANGE n_bi1_rate_factor                 : parameter
    RANGE n_bi1_rate_power                  : parameter
    RANGE n_bi1_rate_base_q10               : parameter
    RANGE n_bi1_rate_TENDEGREES             : parameter
    
    RANGE n_bi1_rate_r                      : exposure
    RANGE n_fi2_SEC                         : parameter
    
    RANGE n_fi2_rf                          : exposure
    
    RANGE n_fi2_rr                          : exposure
    RANGE n_fi2_rate_rate                   : parameter
    RANGE n_fi2_rate_factor                 : parameter
    RANGE n_fi2_rate_power                  : parameter
    RANGE n_fi2_rate_base_q10               : parameter
    RANGE n_fi2_rate_TENDEGREES             : parameter
    
    RANGE n_fi2_rate_r                      : exposure
    RANGE n_bi2_SEC                         : parameter
    
    RANGE n_bi2_rf                          : exposure
    
    RANGE n_bi2_rr                          : exposure
    RANGE n_bi2_rate_rate                   : parameter
    RANGE n_bi2_rate_factor                 : parameter
    RANGE n_bi2_rate_power                  : parameter
    RANGE n_bi2_rate_base_q10               : parameter
    RANGE n_bi2_rate_TENDEGREES             : parameter
    
    RANGE n_bi2_rate_r                      : exposure
    RANGE n_fi3_SEC                         : parameter
    
    RANGE n_fi3_rf                          : exposure
    
    RANGE n_fi3_rr                          : exposure
    RANGE n_fi3_rate_rate                   : parameter
    RANGE n_fi3_rate_factor                 : parameter
    RANGE n_fi3_rate_power                  : parameter
    RANGE n_fi3_rate_base_q10               : parameter
    RANGE n_fi3_rate_TENDEGREES             : parameter
    
    RANGE n_fi3_rate_r                      : exposure
    RANGE n_bi3_SEC                         : parameter
    
    RANGE n_bi3_rf                          : exposure
    
    RANGE n_bi3_rr                          : exposure
    RANGE n_bi3_rate_rate                   : parameter
    RANGE n_bi3_rate_factor                 : parameter
    RANGE n_bi3_rate_power                  : parameter
    RANGE n_bi3_rate_base_q10               : parameter
    RANGE n_bi3_rate_TENDEGREES             : parameter
    
    RANGE n_bi3_rate_r                      : exposure
    RANGE n_fi4_SEC                         : parameter
    
    RANGE n_fi4_rf                          : exposure
    
    RANGE n_fi4_rr                          : exposure
    RANGE n_fi4_rate_rate                   : parameter
    RANGE n_fi4_rate_factor                 : parameter
    RANGE n_fi4_rate_power                  : parameter
    RANGE n_fi4_rate_base_q10               : parameter
    RANGE n_fi4_rate_TENDEGREES             : parameter
    
    RANGE n_fi4_rate_r                      : exposure
    RANGE n_bi4_SEC                         : parameter
    
    RANGE n_bi4_rf                          : exposure
    
    RANGE n_bi4_rr                          : exposure
    RANGE n_bi4_rate_rate                   : parameter
    RANGE n_bi4_rate_factor                 : parameter
    RANGE n_bi4_rate_power                  : parameter
    RANGE n_bi4_rate_base_q10               : parameter
    RANGE n_bi4_rate_TENDEGREES             : parameter
    
    RANGE n_bi4_rate_r                      : exposure
    RANGE n_fi5_SEC                         : parameter
    
    RANGE n_fi5_rf                          : exposure
    
    RANGE n_fi5_rr                          : exposure
    RANGE n_fi5_rate_rate                   : parameter
    RANGE n_fi5_rate_factor                 : parameter
    RANGE n_fi5_rate_power                  : parameter
    RANGE n_fi5_rate_base_q10               : parameter
    RANGE n_fi5_rate_TENDEGREES             : parameter
    
    RANGE n_fi5_rate_r                      : exposure
    RANGE n_bi5_SEC                         : parameter
    
    RANGE n_bi5_rf                          : exposure
    
    RANGE n_bi5_rr                          : exposure
    RANGE n_bi5_rate_rate                   : parameter
    RANGE n_bi5_rate_factor                 : parameter
    RANGE n_bi5_rate_power                  : parameter
    RANGE n_bi5_rate_base_q10               : parameter
    RANGE n_bi5_rate_TENDEGREES             : parameter
    
    RANGE n_bi5_rate_r                      : exposure
    RANGE n_f01_rate_qt                     : derived variable
    RANGE n_f01_rf0                         : derived variable
    RANGE n_b01_rate_qt                     : derived variable
    RANGE n_b01_rr0                         : derived variable
    RANGE n_f02_rate_qt                     : derived variable
    RANGE n_f02_rf0                         : derived variable
    RANGE n_b02_rate_qt                     : derived variable
    RANGE n_b02_rr0                         : derived variable
    RANGE n_f03_rate_qt                     : derived variable
    RANGE n_f03_rf0                         : derived variable
    RANGE n_b03_rate_qt                     : derived variable
    RANGE n_b03_rr0                         : derived variable
    RANGE n_f04_rate_qt                     : derived variable
    RANGE n_f04_rf0                         : derived variable
    RANGE n_b04_rate_qt                     : derived variable
    RANGE n_b04_rr0                         : derived variable
    RANGE n_f00_rate_qt                     : derived variable
    RANGE n_f00_rf0                         : derived variable
    RANGE n_b00_rate_qt                     : derived variable
    RANGE n_b00_rr0                         : derived variable
    RANGE n_fin_rate_qt                     : derived variable
    RANGE n_fin_rf0                         : derived variable
    RANGE n_bin_rate_qt                     : derived variable
    RANGE n_bin_rr0                         : derived variable
    RANGE n_f11_rate_qt                     : derived variable
    RANGE n_f11_rf0                         : derived variable
    RANGE n_b11_rate_qt                     : derived variable
    RANGE n_b11_rr0                         : derived variable
    RANGE n_f12_rate_qt                     : derived variable
    RANGE n_f12_rf0                         : derived variable
    RANGE n_b12_rate_qt                     : derived variable
    RANGE n_b12_rr0                         : derived variable
    RANGE n_f13_rate_qt                     : derived variable
    RANGE n_f13_rf0                         : derived variable
    RANGE n_b13_rate_qt                     : derived variable
    RANGE n_b13_rr0                         : derived variable
    RANGE n_f14_rate_qt                     : derived variable
    RANGE n_f14_rf0                         : derived variable
    RANGE n_b14_rate_qt                     : derived variable
    RANGE n_b14_rr0                         : derived variable
    RANGE n_f1n_rate_qt                     : derived variable
    RANGE n_f1n_rf0                         : derived variable
    RANGE n_b1n_rate_qt                     : derived variable
    RANGE n_b1n_rr0                         : derived variable
    RANGE n_fi1_rate_qt                     : derived variable
    RANGE n_fi1_rf0                         : derived variable
    RANGE n_bi1_rate_qt                     : derived variable
    RANGE n_bi1_rr0                         : derived variable
    RANGE n_fi2_rate_qt                     : derived variable
    RANGE n_fi2_rf0                         : derived variable
    RANGE n_bi2_rate_qt                     : derived variable
    RANGE n_bi2_rr0                         : derived variable
    RANGE n_fi3_rate_qt                     : derived variable
    RANGE n_fi3_rf0                         : derived variable
    RANGE n_bi3_rate_qt                     : derived variable
    RANGE n_bi3_rr0                         : derived variable
    RANGE n_fi4_rate_qt                     : derived variable
    RANGE n_fi4_rf0                         : derived variable
    RANGE n_bi4_rate_qt                     : derived variable
    RANGE n_bi4_rr0                         : derived variable
    RANGE n_fi5_rate_qt                     : derived variable
    RANGE n_fi5_rf0                         : derived variable
    RANGE n_bi5_rate_qt                     : derived variable
    RANGE n_bi5_rr0                         : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)
    n_instances = 1 
    n_C1_relativeConductance = 0 
    n_C2_relativeConductance = 0 
    n_C3_relativeConductance = 0 
    n_C4_relativeConductance = 0 
    n_C5_relativeConductance = 0 
    n_I1_relativeConductance = 0 
    n_I2_relativeConductance = 0 
    n_I3_relativeConductance = 0 
    n_I4_relativeConductance = 0 
    n_I5_relativeConductance = 0 
    n_I6_relativeConductance = 0 
    n_O_relativeConductance = 1 
    n_f01_SEC = 1000 (ms)
    n_f01_rate_forward_n = 4 
    n_f01_rate_backward_n = 0 
    n_f01_rate_alfac = 1 
    n_f01_rate_btfac = 1 
    n_f01_rate_alpha = 400.00003 (kHz)
    n_f01_rate_beta = 12.000001 (kHz)
    n_f01_rate_x1 = 24 (mV)
    n_f01_rate_x2 = -24 (mV)
    n_f01_rate_base_q10 = 310.15 (K)
    n_f01_rate_TENDEGREES = 10 (K)
    n_b01_SEC = 1000 (ms)
    n_b01_rate_forward_n = 0 
    n_b01_rate_backward_n = 1 
    n_b01_rate_alfac = 1 
    n_b01_rate_btfac = 1 
    n_b01_rate_alpha = 400.00003 (kHz)
    n_b01_rate_beta = 12.000001 (kHz)
    n_b01_rate_x1 = 24 (mV)
    n_b01_rate_x2 = -24 (mV)
    n_b01_rate_base_q10 = 310.15 (K)
    n_b01_rate_TENDEGREES = 10 (K)
    n_f02_SEC = 1000 (ms)
    n_f02_rate_forward_n = 3 
    n_f02_rate_backward_n = 0 
    n_f02_rate_alfac = 1 
    n_f02_rate_btfac = 1 
    n_f02_rate_alpha = 400.00003 (kHz)
    n_f02_rate_beta = 12.000001 (kHz)
    n_f02_rate_x1 = 24 (mV)
    n_f02_rate_x2 = -24 (mV)
    n_f02_rate_base_q10 = 310.15 (K)
    n_f02_rate_TENDEGREES = 10 (K)
    n_b02_SEC = 1000 (ms)
    n_b02_rate_forward_n = 0 
    n_b02_rate_backward_n = 2 
    n_b02_rate_alfac = 1 
    n_b02_rate_btfac = 1 
    n_b02_rate_alpha = 400.00003 (kHz)
    n_b02_rate_beta = 12.000001 (kHz)
    n_b02_rate_x1 = 24 (mV)
    n_b02_rate_x2 = -24 (mV)
    n_b02_rate_base_q10 = 310.15 (K)
    n_b02_rate_TENDEGREES = 10 (K)
    n_f03_SEC = 1000 (ms)
    n_f03_rate_forward_n = 2 
    n_f03_rate_backward_n = 0 
    n_f03_rate_alfac = 1 
    n_f03_rate_btfac = 1 
    n_f03_rate_alpha = 400.00003 (kHz)
    n_f03_rate_beta = 12.000001 (kHz)
    n_f03_rate_x1 = 24 (mV)
    n_f03_rate_x2 = -24 (mV)
    n_f03_rate_base_q10 = 310.15 (K)
    n_f03_rate_TENDEGREES = 10 (K)
    n_b03_SEC = 1000 (ms)
    n_b03_rate_forward_n = 0 
    n_b03_rate_backward_n = 3 
    n_b03_rate_alfac = 1 
    n_b03_rate_btfac = 1 
    n_b03_rate_alpha = 400.00003 (kHz)
    n_b03_rate_beta = 12.000001 (kHz)
    n_b03_rate_x1 = 24 (mV)
    n_b03_rate_x2 = -24 (mV)
    n_b03_rate_base_q10 = 310.15 (K)
    n_b03_rate_TENDEGREES = 10 (K)
    n_f04_SEC = 1000 (ms)
    n_f04_rate_forward_n = 1 
    n_f04_rate_backward_n = 0 
    n_f04_rate_alfac = 1 
    n_f04_rate_btfac = 1 
    n_f04_rate_alpha = 400.00003 (kHz)
    n_f04_rate_beta = 12.000001 (kHz)
    n_f04_rate_x1 = 24 (mV)
    n_f04_rate_x2 = -24 (mV)
    n_f04_rate_base_q10 = 310.15 (K)
    n_f04_rate_TENDEGREES = 10 (K)
    n_b04_SEC = 1000 (ms)
    n_b04_rate_forward_n = 0 
    n_b04_rate_backward_n = 4 
    n_b04_rate_alfac = 1 
    n_b04_rate_btfac = 1 
    n_b04_rate_alpha = 400.00003 (kHz)
    n_b04_rate_beta = 12.000001 (kHz)
    n_b04_rate_x1 = 24 (mV)
    n_b04_rate_x2 = -24 (mV)
    n_b04_rate_base_q10 = 310.15 (K)
    n_b04_rate_TENDEGREES = 10 (K)
    n_f00_SEC = 1000 (ms)
    n_f00_rate_rate = 250.00002 (kHz)
    n_f00_rate_factor = 1 
    n_f00_rate_power = 0 
    n_f00_rate_base_q10 = 310.15 (K)
    n_f00_rate_TENDEGREES = 10 (K)
    n_b00_SEC = 1000 (ms)
    n_b00_rate_rate = 60.000004 (kHz)
    n_b00_rate_factor = 1 
    n_b00_rate_power = 0 
    n_b00_rate_base_q10 = 310.15 (K)
    n_b00_rate_TENDEGREES = 10 (K)
    n_fin_SEC = 1000 (ms)
    n_fin_rate_rate = 8 (kHz)
    n_fin_rate_factor = 1 
    n_fin_rate_power = 0 
    n_fin_rate_base_q10 = 310.15 (K)
    n_fin_rate_TENDEGREES = 10 (K)
    n_bin_SEC = 1000 (ms)
    n_bin_rate_rate = 0.05 (kHz)
    n_bin_rate_factor = 1 
    n_bin_rate_power = 0 
    n_bin_rate_base_q10 = 310.15 (K)
    n_bin_rate_TENDEGREES = 10 (K)
    n_f11_SEC = 1000 (ms)
    n_f11_rate_forward_n = 4 
    n_f11_rate_backward_n = 0 
    n_f11_rate_alfac = 2.51 
    n_f11_rate_btfac = 1 
    n_f11_rate_alpha = 400.00003 (kHz)
    n_f11_rate_beta = 12.000001 (kHz)
    n_f11_rate_x1 = 24 (mV)
    n_f11_rate_x2 = -24 (mV)
    n_f11_rate_base_q10 = 310.15 (K)
    n_f11_rate_TENDEGREES = 10 (K)
    n_b11_SEC = 1000 (ms)
    n_b11_rate_forward_n = 0 
    n_b11_rate_backward_n = 1 
    n_b11_rate_alfac = 1 
    n_b11_rate_btfac = 5.32 
    n_b11_rate_alpha = 400.00003 (kHz)
    n_b11_rate_beta = 12.000001 (kHz)
    n_b11_rate_x1 = 24 (mV)
    n_b11_rate_x2 = -24 (mV)
    n_b11_rate_base_q10 = 310.15 (K)
    n_b11_rate_TENDEGREES = 10 (K)
    n_f12_SEC = 1000 (ms)
    n_f12_rate_forward_n = 3 
    n_f12_rate_backward_n = 0 
    n_f12_rate_alfac = 2.51 
    n_f12_rate_btfac = 1 
    n_f12_rate_alpha = 400.00003 (kHz)
    n_f12_rate_beta = 12.000001 (kHz)
    n_f12_rate_x1 = 24 (mV)
    n_f12_rate_x2 = -24 (mV)
    n_f12_rate_base_q10 = 310.15 (K)
    n_f12_rate_TENDEGREES = 10 (K)
    n_b12_SEC = 1000 (ms)
    n_b12_rate_forward_n = 0 
    n_b12_rate_backward_n = 2 
    n_b12_rate_alfac = 1 
    n_b12_rate_btfac = 5.32 
    n_b12_rate_alpha = 400.00003 (kHz)
    n_b12_rate_beta = 12.000001 (kHz)
    n_b12_rate_x1 = 24 (mV)
    n_b12_rate_x2 = -24 (mV)
    n_b12_rate_base_q10 = 310.15 (K)
    n_b12_rate_TENDEGREES = 10 (K)
    n_f13_SEC = 1000 (ms)
    n_f13_rate_forward_n = 2 
    n_f13_rate_backward_n = 0 
    n_f13_rate_alfac = 2.51 
    n_f13_rate_btfac = 1 
    n_f13_rate_alpha = 400.00003 (kHz)
    n_f13_rate_beta = 12.000001 (kHz)
    n_f13_rate_x1 = 24 (mV)
    n_f13_rate_x2 = -24 (mV)
    n_f13_rate_base_q10 = 310.15 (K)
    n_f13_rate_TENDEGREES = 10 (K)
    n_b13_SEC = 1000 (ms)
    n_b13_rate_forward_n = 0 
    n_b13_rate_backward_n = 3 
    n_b13_rate_alfac = 1 
    n_b13_rate_btfac = 5.32 
    n_b13_rate_alpha = 400.00003 (kHz)
    n_b13_rate_beta = 12.000001 (kHz)
    n_b13_rate_x1 = 24 (mV)
    n_b13_rate_x2 = -24 (mV)
    n_b13_rate_base_q10 = 310.15 (K)
    n_b13_rate_TENDEGREES = 10 (K)
    n_f14_SEC = 1000 (ms)
    n_f14_rate_forward_n = 1 
    n_f14_rate_backward_n = 0 
    n_f14_rate_alfac = 2.51 
    n_f14_rate_btfac = 1 
    n_f14_rate_alpha = 400.00003 (kHz)
    n_f14_rate_beta = 12.000001 (kHz)
    n_f14_rate_x1 = 24 (mV)
    n_f14_rate_x2 = -24 (mV)
    n_f14_rate_base_q10 = 310.15 (K)
    n_f14_rate_TENDEGREES = 10 (K)
    n_b14_SEC = 1000 (ms)
    n_b14_rate_forward_n = 0 
    n_b14_rate_backward_n = 4 
    n_b14_rate_alfac = 1 
    n_b14_rate_btfac = 5.32 
    n_b14_rate_alpha = 400.00003 (kHz)
    n_b14_rate_beta = 12.000001 (kHz)
    n_b14_rate_x1 = 24 (mV)
    n_b14_rate_x2 = -24 (mV)
    n_b14_rate_base_q10 = 310.15 (K)
    n_b14_rate_TENDEGREES = 10 (K)
    n_f1n_SEC = 1000 (ms)
    n_f1n_rate_rate = 250.00002 (kHz)
    n_f1n_rate_factor = 1 
    n_f1n_rate_power = 0 
    n_f1n_rate_base_q10 = 310.15 (K)
    n_f1n_rate_TENDEGREES = 10 (K)
    n_b1n_SEC = 1000 (ms)
    n_b1n_rate_rate = 60.000004 (kHz)
    n_b1n_rate_factor = 1 
    n_b1n_rate_power = 0 
    n_b1n_rate_base_q10 = 310.15 (K)
    n_b1n_rate_TENDEGREES = 10 (K)
    n_fi1_SEC = 1000 (ms)
    n_fi1_rate_rate = 0.010000001 (kHz)
    n_fi1_rate_factor = 1 
    n_fi1_rate_power = 0 
    n_fi1_rate_base_q10 = 310.15 (K)
    n_fi1_rate_TENDEGREES = 10 (K)
    n_bi1_SEC = 1000 (ms)
    n_bi1_rate_rate = 40 (kHz)
    n_bi1_rate_factor = 1 
    n_bi1_rate_power = 0 
    n_bi1_rate_base_q10 = 310.15 (K)
    n_bi1_rate_TENDEGREES = 10 (K)
    n_fi2_SEC = 1000 (ms)
    n_fi2_rate_rate = 0.010000001 (kHz)
    n_fi2_rate_factor = 2.51 
    n_fi2_rate_power = 1 
    n_fi2_rate_base_q10 = 310.15 (K)
    n_fi2_rate_TENDEGREES = 10 (K)
    n_bi2_SEC = 1000 (ms)
    n_bi2_rate_rate = 40 (kHz)
    n_bi2_rate_factor = 5.32 
    n_bi2_rate_power = -1 
    n_bi2_rate_base_q10 = 310.15 (K)
    n_bi2_rate_TENDEGREES = 10 (K)
    n_fi3_SEC = 1000 (ms)
    n_fi3_rate_rate = 0.010000001 (kHz)
    n_fi3_rate_factor = 2.51 
    n_fi3_rate_power = 2 
    n_fi3_rate_base_q10 = 310.15 (K)
    n_fi3_rate_TENDEGREES = 10 (K)
    n_bi3_SEC = 1000 (ms)
    n_bi3_rate_rate = 40 (kHz)
    n_bi3_rate_factor = 5.32 
    n_bi3_rate_power = -2 
    n_bi3_rate_base_q10 = 310.15 (K)
    n_bi3_rate_TENDEGREES = 10 (K)
    n_fi4_SEC = 1000 (ms)
    n_fi4_rate_rate = 0.010000001 (kHz)
    n_fi4_rate_factor = 2.51 
    n_fi4_rate_power = 3 
    n_fi4_rate_base_q10 = 310.15 (K)
    n_fi4_rate_TENDEGREES = 10 (K)
    n_bi4_SEC = 1000 (ms)
    n_bi4_rate_rate = 40 (kHz)
    n_bi4_rate_factor = 5.32 
    n_bi4_rate_power = -3 
    n_bi4_rate_base_q10 = 310.15 (K)
    n_bi4_rate_TENDEGREES = 10 (K)
    n_fi5_SEC = 1000 (ms)
    n_fi5_rate_rate = 0.010000001 (kHz)
    n_fi5_rate_factor = 2.51 
    n_fi5_rate_power = 4 
    n_fi5_rate_base_q10 = 310.15 (K)
    n_fi5_rate_TENDEGREES = 10 (K)
    n_bi5_SEC = 1000 (ms)
    n_bi5_rate_rate = 40 (kHz)
    n_bi5_rate_factor = 5.32 
    n_bi5_rate_power = -4 
    n_bi5_rate_base_q10 = 310.15 (K)
    n_bi5_rate_TENDEGREES = 10 (K)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ena (mV)
    ina (mA/cm2)
    
    
    n_C1_q                                 : derived variable
    
    n_C2_q                                 : derived variable
    
    n_C3_q                                 : derived variable
    
    n_C4_q                                 : derived variable
    
    n_C5_q                                 : derived variable
    
    n_I1_q                                 : derived variable
    
    n_I2_q                                 : derived variable
    
    n_I3_q                                 : derived variable
    
    n_I4_q                                 : derived variable
    
    n_I5_q                                 : derived variable
    
    n_I6_q                                 : derived variable
    
    n_O_q                                  : derived variable
    
    n_f01_rate_qt                          : derived variable
    
    n_f01_rate_r (kHz)                     : derived variable
    
    n_f01_rf0 (kHz)                        : derived variable
    
    n_f01_rf (kHz)                         : derived variable
    
    n_f01_rr (kHz)                         : derived variable
    
    n_b01_rate_qt                          : derived variable
    
    n_b01_rate_r (kHz)                     : derived variable
    
    n_b01_rr0 (kHz)                        : derived variable
    
    n_b01_rr (kHz)                         : derived variable
    
    n_b01_rf (kHz)                         : derived variable
    
    n_f02_rate_qt                          : derived variable
    
    n_f02_rate_r (kHz)                     : derived variable
    
    n_f02_rf0 (kHz)                        : derived variable
    
    n_f02_rf (kHz)                         : derived variable
    
    n_f02_rr (kHz)                         : derived variable
    
    n_b02_rate_qt                          : derived variable
    
    n_b02_rate_r (kHz)                     : derived variable
    
    n_b02_rr0 (kHz)                        : derived variable
    
    n_b02_rr (kHz)                         : derived variable
    
    n_b02_rf (kHz)                         : derived variable
    
    n_f03_rate_qt                          : derived variable
    
    n_f03_rate_r (kHz)                     : derived variable
    
    n_f03_rf0 (kHz)                        : derived variable
    
    n_f03_rf (kHz)                         : derived variable
    
    n_f03_rr (kHz)                         : derived variable
    
    n_b03_rate_qt                          : derived variable
    
    n_b03_rate_r (kHz)                     : derived variable
    
    n_b03_rr0 (kHz)                        : derived variable
    
    n_b03_rr (kHz)                         : derived variable
    
    n_b03_rf (kHz)                         : derived variable
    
    n_f04_rate_qt                          : derived variable
    
    n_f04_rate_r (kHz)                     : derived variable
    
    n_f04_rf0 (kHz)                        : derived variable
    
    n_f04_rf (kHz)                         : derived variable
    
    n_f04_rr (kHz)                         : derived variable
    
    n_b04_rate_qt                          : derived variable
    
    n_b04_rate_r (kHz)                     : derived variable
    
    n_b04_rr0 (kHz)                        : derived variable
    
    n_b04_rr (kHz)                         : derived variable
    
    n_b04_rf (kHz)                         : derived variable
    
    n_f00_rate_qt                          : derived variable
    
    n_f00_rate_r (kHz)                     : derived variable
    
    n_f00_rf0 (kHz)                        : derived variable
    
    n_f00_rf (kHz)                         : derived variable
    
    n_f00_rr (kHz)                         : derived variable
    
    n_b00_rate_qt                          : derived variable
    
    n_b00_rate_r (kHz)                     : derived variable
    
    n_b00_rr0 (kHz)                        : derived variable
    
    n_b00_rr (kHz)                         : derived variable
    
    n_b00_rf (kHz)                         : derived variable
    
    n_fin_rate_qt                          : derived variable
    
    n_fin_rate_r (kHz)                     : derived variable
    
    n_fin_rf0 (kHz)                        : derived variable
    
    n_fin_rf (kHz)                         : derived variable
    
    n_fin_rr (kHz)                         : derived variable
    
    n_bin_rate_qt                          : derived variable
    
    n_bin_rate_r (kHz)                     : derived variable
    
    n_bin_rr0 (kHz)                        : derived variable
    
    n_bin_rr (kHz)                         : derived variable
    
    n_bin_rf (kHz)                         : derived variable
    
    n_f11_rate_qt                          : derived variable
    
    n_f11_rate_r (kHz)                     : derived variable
    
    n_f11_rf0 (kHz)                        : derived variable
    
    n_f11_rf (kHz)                         : derived variable
    
    n_f11_rr (kHz)                         : derived variable
    
    n_b11_rate_qt                          : derived variable
    
    n_b11_rate_r (kHz)                     : derived variable
    
    n_b11_rr0 (kHz)                        : derived variable
    
    n_b11_rr (kHz)                         : derived variable
    
    n_b11_rf (kHz)                         : derived variable
    
    n_f12_rate_qt                          : derived variable
    
    n_f12_rate_r (kHz)                     : derived variable
    
    n_f12_rf0 (kHz)                        : derived variable
    
    n_f12_rf (kHz)                         : derived variable
    
    n_f12_rr (kHz)                         : derived variable
    
    n_b12_rate_qt                          : derived variable
    
    n_b12_rate_r (kHz)                     : derived variable
    
    n_b12_rr0 (kHz)                        : derived variable
    
    n_b12_rr (kHz)                         : derived variable
    
    n_b12_rf (kHz)                         : derived variable
    
    n_f13_rate_qt                          : derived variable
    
    n_f13_rate_r (kHz)                     : derived variable
    
    n_f13_rf0 (kHz)                        : derived variable
    
    n_f13_rf (kHz)                         : derived variable
    
    n_f13_rr (kHz)                         : derived variable
    
    n_b13_rate_qt                          : derived variable
    
    n_b13_rate_r (kHz)                     : derived variable
    
    n_b13_rr0 (kHz)                        : derived variable
    
    n_b13_rr (kHz)                         : derived variable
    
    n_b13_rf (kHz)                         : derived variable
    
    n_f14_rate_qt                          : derived variable
    
    n_f14_rate_r (kHz)                     : derived variable
    
    n_f14_rf0 (kHz)                        : derived variable
    
    n_f14_rf (kHz)                         : derived variable
    
    n_f14_rr (kHz)                         : derived variable
    
    n_b14_rate_qt                          : derived variable
    
    n_b14_rate_r (kHz)                     : derived variable
    
    n_b14_rr0 (kHz)                        : derived variable
    
    n_b14_rr (kHz)                         : derived variable
    
    n_b14_rf (kHz)                         : derived variable
    
    n_f1n_rate_qt                          : derived variable
    
    n_f1n_rate_r (kHz)                     : derived variable
    
    n_f1n_rf0 (kHz)                        : derived variable
    
    n_f1n_rf (kHz)                         : derived variable
    
    n_f1n_rr (kHz)                         : derived variable
    
    n_b1n_rate_qt                          : derived variable
    
    n_b1n_rate_r (kHz)                     : derived variable
    
    n_b1n_rr0 (kHz)                        : derived variable
    
    n_b1n_rr (kHz)                         : derived variable
    
    n_b1n_rf (kHz)                         : derived variable
    
    n_fi1_rate_qt                          : derived variable
    
    n_fi1_rate_r (kHz)                     : derived variable
    
    n_fi1_rf0 (kHz)                        : derived variable
    
    n_fi1_rf (kHz)                         : derived variable
    
    n_fi1_rr (kHz)                         : derived variable
    
    n_bi1_rate_qt                          : derived variable
    
    n_bi1_rate_r (kHz)                     : derived variable
    
    n_bi1_rr0 (kHz)                        : derived variable
    
    n_bi1_rr (kHz)                         : derived variable
    
    n_bi1_rf (kHz)                         : derived variable
    
    n_fi2_rate_qt                          : derived variable
    
    n_fi2_rate_r (kHz)                     : derived variable
    
    n_fi2_rf0 (kHz)                        : derived variable
    
    n_fi2_rf (kHz)                         : derived variable
    
    n_fi2_rr (kHz)                         : derived variable
    
    n_bi2_rate_qt                          : derived variable
    
    n_bi2_rate_r (kHz)                     : derived variable
    
    n_bi2_rr0 (kHz)                        : derived variable
    
    n_bi2_rr (kHz)                         : derived variable
    
    n_bi2_rf (kHz)                         : derived variable
    
    n_fi3_rate_qt                          : derived variable
    
    n_fi3_rate_r (kHz)                     : derived variable
    
    n_fi3_rf0 (kHz)                        : derived variable
    
    n_fi3_rf (kHz)                         : derived variable
    
    n_fi3_rr (kHz)                         : derived variable
    
    n_bi3_rate_qt                          : derived variable
    
    n_bi3_rate_r (kHz)                     : derived variable
    
    n_bi3_rr0 (kHz)                        : derived variable
    
    n_bi3_rr (kHz)                         : derived variable
    
    n_bi3_rf (kHz)                         : derived variable
    
    n_fi4_rate_qt                          : derived variable
    
    n_fi4_rate_r (kHz)                     : derived variable
    
    n_fi4_rf0 (kHz)                        : derived variable
    
    n_fi4_rf (kHz)                         : derived variable
    
    n_fi4_rr (kHz)                         : derived variable
    
    n_bi4_rate_qt                          : derived variable
    
    n_bi4_rate_r (kHz)                     : derived variable
    
    n_bi4_rr0 (kHz)                        : derived variable
    
    n_bi4_rr (kHz)                         : derived variable
    
    n_bi4_rf (kHz)                         : derived variable
    
    n_fi5_rate_qt                          : derived variable
    
    n_fi5_rate_r (kHz)                     : derived variable
    
    n_fi5_rf0 (kHz)                        : derived variable
    
    n_fi5_rf (kHz)                         : derived variable
    
    n_fi5_rr (kHz)                         : derived variable
    
    n_bi5_rate_qt                          : derived variable
    
    n_bi5_rate_r (kHz)                     : derived variable
    
    n_bi5_rr0 (kHz)                        : derived variable
    
    n_bi5_rr (kHz)                         : derived variable
    
    n_bi5_rf (kHz)                         : derived variable
    
    n_rateScale                            : derived variable
    
    n_q                                    : derived variable
    
    n_fcond                                : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    
}

STATE {
    n_C1_occupancy FROM 0 TO 1  
    n_C2_occupancy FROM 0 TO 1  
    n_C3_occupancy FROM 0 TO 1  
    n_C4_occupancy FROM 0 TO 1  
    n_C5_occupancy FROM 0 TO 1  
    n_I1_occupancy FROM 0 TO 1  
    n_I2_occupancy FROM 0 TO 1  
    n_I3_occupancy FROM 0 TO 1  
    n_I4_occupancy FROM 0 TO 1  
    n_I5_occupancy FROM 0 TO 1  
    n_I6_occupancy FROM 0 TO 1  
    n_O_occupancy FROM 0 TO 1  
    
}

INITIAL {
    ena = 53.0
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    SOLVE activation STEADYSTATE sparse
    
}

BREAKPOINT {
    
    SOLVE activation METHOD sparse ? NaV (Type: ionChannelKS:  conductance=1.0E-11 (SI conductance))
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=NaV type=ionChannelKS), from gates; Component(id=n type=gateKS)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=n type=gateKS)]))
    fopen = n_fcond ? path based, prefix = 
    
    g = fopen  *  conductance ? evaluable
    gion = gmax * fopen 
    
    ina = gion * (v - ena)
    
}

KINETIC activation {
    rates()
    
    ~ n_C1_occupancy <-> n_C2_occupancy    (n_f01_rate_r,n_b01_rate_r)
    ~ n_C2_occupancy <-> n_C3_occupancy    (n_f02_rate_r,n_b02_rate_r)
    ~ n_C3_occupancy <-> n_C4_occupancy    (n_f03_rate_r,n_b03_rate_r)
    ~ n_C4_occupancy <-> n_C5_occupancy    (n_f04_rate_r,n_b04_rate_r)
    ~ n_C5_occupancy <-> n_O_occupancy    (n_f00_rate_r,n_b00_rate_r)
    ~ n_O_occupancy <-> n_I6_occupancy    (n_fin_rate_r,n_bin_rate_r)
    ~ n_I1_occupancy <-> n_I2_occupancy    (n_f11_rate_r,n_b11_rate_r)
    ~ n_I2_occupancy <-> n_I3_occupancy    (n_f12_rate_r,n_b12_rate_r)
    ~ n_I3_occupancy <-> n_I4_occupancy    (n_f13_rate_r,n_b13_rate_r)
    ~ n_I4_occupancy <-> n_I5_occupancy    (n_f14_rate_r,n_b14_rate_r)
    ~ n_I5_occupancy <-> n_I6_occupancy    (n_f1n_rate_r,n_b1n_rate_r)
    ~ n_C1_occupancy <-> n_I1_occupancy    (n_fi1_rate_r,n_bi1_rate_r)
    ~ n_C2_occupancy <-> n_I2_occupancy    (n_fi2_rate_r,n_bi2_rate_r)
    ~ n_C3_occupancy <-> n_I3_occupancy    (n_fi3_rate_r,n_bi3_rate_r)
    ~ n_C4_occupancy <-> n_I4_occupancy    (n_fi4_rate_r,n_bi4_rate_r)
    ~ n_C5_occupancy <-> n_I5_occupancy    (n_fi5_rate_r,n_bi5_rate_r)
    CONSERVE n_C2_occupancy+n_I2_occupancy+n_C1_occupancy+n_I1_occupancy+n_I3_occupancy+n_I6_occupancy+n_C4_occupancy+n_O_occupancy+n_I4_occupancy+n_C3_occupancy+n_C5_occupancy+n_I5_occupancy= 1
    
    
}

PROCEDURE rates() {
    
    n_C1_q = n_C1_relativeConductance  *  n_C1_occupancy ? evaluable
    n_C2_q = n_C2_relativeConductance  *  n_C2_occupancy ? evaluable
    n_C3_q = n_C3_relativeConductance  *  n_C3_occupancy ? evaluable
    n_C4_q = n_C4_relativeConductance  *  n_C4_occupancy ? evaluable
    n_C5_q = n_C5_relativeConductance  *  n_C5_occupancy ? evaluable
    n_I1_q = n_I1_relativeConductance  *  n_I1_occupancy ? evaluable
    n_I2_q = n_I2_relativeConductance  *  n_I2_occupancy ? evaluable
    n_I3_q = n_I3_relativeConductance  *  n_I3_occupancy ? evaluable
    n_I4_q = n_I4_relativeConductance  *  n_I4_occupancy ? evaluable
    n_I5_q = n_I5_relativeConductance  *  n_I5_occupancy ? evaluable
    n_I6_q = n_I6_relativeConductance  *  n_I6_occupancy ? evaluable
    n_O_q = n_O_relativeConductance  *  n_O_occupancy ? evaluable
    n_f01_rate_qt = 2.3^((temperature- n_f01_rate_base_q10 )/ n_f01_rate_TENDEGREES ) ? evaluable
    n_f01_rate_r = ( n_f01_rate_qt  *  n_f01_rate_forward_n  *  n_f01_rate_alpha  *  n_f01_rate_alfac  * exp(v/ n_f01_rate_x1 )) + ( n_f01_rate_qt  *  n_f01_rate_backward_n  *  n_f01_rate_beta  * exp(v/ n_f01_rate_x2 ) /  n_f01_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f01 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f01_rf0 = n_f01_rate_r ? path based, prefix = n_f01_
    
    n_f01_rf = n_f01_rf0 ? evaluable
    n_f01_rr = 0/ n_f01_SEC ? evaluable
    n_b01_rate_qt = 2.3^((temperature- n_b01_rate_base_q10 )/ n_b01_rate_TENDEGREES ) ? evaluable
    n_b01_rate_r = ( n_b01_rate_qt  *  n_b01_rate_forward_n  *  n_b01_rate_alpha  *  n_b01_rate_alfac  * exp(v/ n_b01_rate_x1 )) + ( n_b01_rate_qt  *  n_b01_rate_backward_n  *  n_b01_rate_beta  * exp(v/ n_b01_rate_x2 ) /  n_b01_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b01 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b01_rr0 = n_b01_rate_r ? path based, prefix = n_b01_
    
    n_b01_rr = n_b01_rr0 ? evaluable
    n_b01_rf = 0/ n_b01_SEC ? evaluable
    n_f02_rate_qt = 2.3^((temperature- n_f02_rate_base_q10 )/ n_f02_rate_TENDEGREES ) ? evaluable
    n_f02_rate_r = ( n_f02_rate_qt  *  n_f02_rate_forward_n  *  n_f02_rate_alpha  *  n_f02_rate_alfac  * exp(v/ n_f02_rate_x1 )) + ( n_f02_rate_qt  *  n_f02_rate_backward_n  *  n_f02_rate_beta  * exp(v/ n_f02_rate_x2 ) /  n_f02_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f02 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f02_rf0 = n_f02_rate_r ? path based, prefix = n_f02_
    
    n_f02_rf = n_f02_rf0 ? evaluable
    n_f02_rr = 0/ n_f02_SEC ? evaluable
    n_b02_rate_qt = 2.3^((temperature- n_b02_rate_base_q10 )/ n_b02_rate_TENDEGREES ) ? evaluable
    n_b02_rate_r = ( n_b02_rate_qt  *  n_b02_rate_forward_n  *  n_b02_rate_alpha  *  n_b02_rate_alfac  * exp(v/ n_b02_rate_x1 )) + ( n_b02_rate_qt  *  n_b02_rate_backward_n  *  n_b02_rate_beta  * exp(v/ n_b02_rate_x2 ) /  n_b02_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b02 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b02_rr0 = n_b02_rate_r ? path based, prefix = n_b02_
    
    n_b02_rr = n_b02_rr0 ? evaluable
    n_b02_rf = 0/ n_b02_SEC ? evaluable
    n_f03_rate_qt = 2.3^((temperature- n_f03_rate_base_q10 )/ n_f03_rate_TENDEGREES ) ? evaluable
    n_f03_rate_r = ( n_f03_rate_qt  *  n_f03_rate_forward_n  *  n_f03_rate_alpha  *  n_f03_rate_alfac  * exp(v/ n_f03_rate_x1 )) + ( n_f03_rate_qt  *  n_f03_rate_backward_n  *  n_f03_rate_beta  * exp(v/ n_f03_rate_x2 ) /  n_f03_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f03 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f03_rf0 = n_f03_rate_r ? path based, prefix = n_f03_
    
    n_f03_rf = n_f03_rf0 ? evaluable
    n_f03_rr = 0/ n_f03_SEC ? evaluable
    n_b03_rate_qt = 2.3^((temperature- n_b03_rate_base_q10 )/ n_b03_rate_TENDEGREES ) ? evaluable
    n_b03_rate_r = ( n_b03_rate_qt  *  n_b03_rate_forward_n  *  n_b03_rate_alpha  *  n_b03_rate_alfac  * exp(v/ n_b03_rate_x1 )) + ( n_b03_rate_qt  *  n_b03_rate_backward_n  *  n_b03_rate_beta  * exp(v/ n_b03_rate_x2 ) /  n_b03_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b03 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b03_rr0 = n_b03_rate_r ? path based, prefix = n_b03_
    
    n_b03_rr = n_b03_rr0 ? evaluable
    n_b03_rf = 0/ n_b03_SEC ? evaluable
    n_f04_rate_qt = 2.3^((temperature- n_f04_rate_base_q10 )/ n_f04_rate_TENDEGREES ) ? evaluable
    n_f04_rate_r = ( n_f04_rate_qt  *  n_f04_rate_forward_n  *  n_f04_rate_alpha  *  n_f04_rate_alfac  * exp(v/ n_f04_rate_x1 )) + ( n_f04_rate_qt  *  n_f04_rate_backward_n  *  n_f04_rate_beta  * exp(v/ n_f04_rate_x2 ) /  n_f04_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f04 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f04_rf0 = n_f04_rate_r ? path based, prefix = n_f04_
    
    n_f04_rf = n_f04_rf0 ? evaluable
    n_f04_rr = 0/ n_f04_SEC ? evaluable
    n_b04_rate_qt = 2.3^((temperature- n_b04_rate_base_q10 )/ n_b04_rate_TENDEGREES ) ? evaluable
    n_b04_rate_r = ( n_b04_rate_qt  *  n_b04_rate_forward_n  *  n_b04_rate_alpha  *  n_b04_rate_alfac  * exp(v/ n_b04_rate_x1 )) + ( n_b04_rate_qt  *  n_b04_rate_backward_n  *  n_b04_rate_beta  * exp(v/ n_b04_rate_x2 ) /  n_b04_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b04 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b04_rr0 = n_b04_rate_r ? path based, prefix = n_b04_
    
    n_b04_rr = n_b04_rr0 ? evaluable
    n_b04_rf = 0/ n_b04_SEC ? evaluable
    n_f00_rate_qt = 2.3^((temperature- n_f00_rate_base_q10 )/ n_f00_rate_TENDEGREES ) ? evaluable
    n_f00_rate_r = n_f00_rate_qt  *  n_f00_rate_rate  * ( n_f00_rate_factor ^ n_f00_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f00 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_f00_rf0 = n_f00_rate_r ? path based, prefix = n_f00_
    
    n_f00_rf = n_f00_rf0 ? evaluable
    n_f00_rr = 0/ n_f00_SEC ? evaluable
    n_b00_rate_qt = 2.3^((temperature- n_b00_rate_base_q10 )/ n_b00_rate_TENDEGREES ) ? evaluable
    n_b00_rate_r = n_b00_rate_qt  *  n_b00_rate_rate  * ( n_b00_rate_factor ^ n_b00_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b00 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_b00_rr0 = n_b00_rate_r ? path based, prefix = n_b00_
    
    n_b00_rr = n_b00_rr0 ? evaluable
    n_b00_rf = 0/ n_b00_SEC ? evaluable
    n_fin_rate_qt = 2.3^((temperature- n_fin_rate_base_q10 )/ n_fin_rate_TENDEGREES ) ? evaluable
    n_fin_rate_r = n_fin_rate_qt  *  n_fin_rate_rate  * ( n_fin_rate_factor ^ n_fin_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=fin type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_fin_rf0 = n_fin_rate_r ? path based, prefix = n_fin_
    
    n_fin_rf = n_fin_rf0 ? evaluable
    n_fin_rr = 0/ n_fin_SEC ? evaluable
    n_bin_rate_qt = 2.3^((temperature- n_bin_rate_base_q10 )/ n_bin_rate_TENDEGREES ) ? evaluable
    n_bin_rate_r = n_bin_rate_qt  *  n_bin_rate_rate  * ( n_bin_rate_factor ^ n_bin_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=bin type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_bin_rr0 = n_bin_rate_r ? path based, prefix = n_bin_
    
    n_bin_rr = n_bin_rr0 ? evaluable
    n_bin_rf = 0/ n_bin_SEC ? evaluable
    n_f11_rate_qt = 2.3^((temperature- n_f11_rate_base_q10 )/ n_f11_rate_TENDEGREES ) ? evaluable
    n_f11_rate_r = ( n_f11_rate_qt  *  n_f11_rate_forward_n  *  n_f11_rate_alpha  *  n_f11_rate_alfac  * exp(v/ n_f11_rate_x1 )) + ( n_f11_rate_qt  *  n_f11_rate_backward_n  *  n_f11_rate_beta  * exp(v/ n_f11_rate_x2 ) /  n_f11_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f11 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f11_rf0 = n_f11_rate_r ? path based, prefix = n_f11_
    
    n_f11_rf = n_f11_rf0 ? evaluable
    n_f11_rr = 0/ n_f11_SEC ? evaluable
    n_b11_rate_qt = 2.3^((temperature- n_b11_rate_base_q10 )/ n_b11_rate_TENDEGREES ) ? evaluable
    n_b11_rate_r = ( n_b11_rate_qt  *  n_b11_rate_forward_n  *  n_b11_rate_alpha  *  n_b11_rate_alfac  * exp(v/ n_b11_rate_x1 )) + ( n_b11_rate_qt  *  n_b11_rate_backward_n  *  n_b11_rate_beta  * exp(v/ n_b11_rate_x2 ) /  n_b11_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b11 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b11_rr0 = n_b11_rate_r ? path based, prefix = n_b11_
    
    n_b11_rr = n_b11_rr0 ? evaluable
    n_b11_rf = 0/ n_b11_SEC ? evaluable
    n_f12_rate_qt = 2.3^((temperature- n_f12_rate_base_q10 )/ n_f12_rate_TENDEGREES ) ? evaluable
    n_f12_rate_r = ( n_f12_rate_qt  *  n_f12_rate_forward_n  *  n_f12_rate_alpha  *  n_f12_rate_alfac  * exp(v/ n_f12_rate_x1 )) + ( n_f12_rate_qt  *  n_f12_rate_backward_n  *  n_f12_rate_beta  * exp(v/ n_f12_rate_x2 ) /  n_f12_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f12 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f12_rf0 = n_f12_rate_r ? path based, prefix = n_f12_
    
    n_f12_rf = n_f12_rf0 ? evaluable
    n_f12_rr = 0/ n_f12_SEC ? evaluable
    n_b12_rate_qt = 2.3^((temperature- n_b12_rate_base_q10 )/ n_b12_rate_TENDEGREES ) ? evaluable
    n_b12_rate_r = ( n_b12_rate_qt  *  n_b12_rate_forward_n  *  n_b12_rate_alpha  *  n_b12_rate_alfac  * exp(v/ n_b12_rate_x1 )) + ( n_b12_rate_qt  *  n_b12_rate_backward_n  *  n_b12_rate_beta  * exp(v/ n_b12_rate_x2 ) /  n_b12_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b12 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b12_rr0 = n_b12_rate_r ? path based, prefix = n_b12_
    
    n_b12_rr = n_b12_rr0 ? evaluable
    n_b12_rf = 0/ n_b12_SEC ? evaluable
    n_f13_rate_qt = 2.3^((temperature- n_f13_rate_base_q10 )/ n_f13_rate_TENDEGREES ) ? evaluable
    n_f13_rate_r = ( n_f13_rate_qt  *  n_f13_rate_forward_n  *  n_f13_rate_alpha  *  n_f13_rate_alfac  * exp(v/ n_f13_rate_x1 )) + ( n_f13_rate_qt  *  n_f13_rate_backward_n  *  n_f13_rate_beta  * exp(v/ n_f13_rate_x2 ) /  n_f13_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f13 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f13_rf0 = n_f13_rate_r ? path based, prefix = n_f13_
    
    n_f13_rf = n_f13_rf0 ? evaluable
    n_f13_rr = 0/ n_f13_SEC ? evaluable
    n_b13_rate_qt = 2.3^((temperature- n_b13_rate_base_q10 )/ n_b13_rate_TENDEGREES ) ? evaluable
    n_b13_rate_r = ( n_b13_rate_qt  *  n_b13_rate_forward_n  *  n_b13_rate_alpha  *  n_b13_rate_alfac  * exp(v/ n_b13_rate_x1 )) + ( n_b13_rate_qt  *  n_b13_rate_backward_n  *  n_b13_rate_beta  * exp(v/ n_b13_rate_x2 ) /  n_b13_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b13 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b13_rr0 = n_b13_rate_r ? path based, prefix = n_b13_
    
    n_b13_rr = n_b13_rr0 ? evaluable
    n_b13_rf = 0/ n_b13_SEC ? evaluable
    n_f14_rate_qt = 2.3^((temperature- n_f14_rate_base_q10 )/ n_f14_rate_TENDEGREES ) ? evaluable
    n_f14_rate_r = ( n_f14_rate_qt  *  n_f14_rate_forward_n  *  n_f14_rate_alpha  *  n_f14_rate_alfac  * exp(v/ n_f14_rate_x1 )) + ( n_f14_rate_qt  *  n_f14_rate_backward_n  *  n_f14_rate_beta  * exp(v/ n_f14_rate_x2 ) /  n_f14_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f14 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_f14_rf0 = n_f14_rate_r ? path based, prefix = n_f14_
    
    n_f14_rf = n_f14_rf0 ? evaluable
    n_f14_rr = 0/ n_f14_SEC ? evaluable
    n_b14_rate_qt = 2.3^((temperature- n_b14_rate_base_q10 )/ n_b14_rate_TENDEGREES ) ? evaluable
    n_b14_rate_r = ( n_b14_rate_qt  *  n_b14_rate_forward_n  *  n_b14_rate_alpha  *  n_b14_rate_alfac  * exp(v/ n_b14_rate_x1 )) + ( n_b14_rate_qt  *  n_b14_rate_backward_n  *  n_b14_rate_beta  * exp(v/ n_b14_rate_x2 ) /  n_b14_rate_btfac ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b14 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate1)
    n_b14_rr0 = n_b14_rate_r ? path based, prefix = n_b14_
    
    n_b14_rr = n_b14_rr0 ? evaluable
    n_b14_rf = 0/ n_b14_SEC ? evaluable
    n_f1n_rate_qt = 2.3^((temperature- n_f1n_rate_base_q10 )/ n_f1n_rate_TENDEGREES ) ? evaluable
    n_f1n_rate_r = n_f1n_rate_qt  *  n_f1n_rate_rate  * ( n_f1n_rate_factor ^ n_f1n_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=f1n type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_f1n_rf0 = n_f1n_rate_r ? path based, prefix = n_f1n_
    
    n_f1n_rf = n_f1n_rf0 ? evaluable
    n_f1n_rr = 0/ n_f1n_SEC ? evaluable
    n_b1n_rate_qt = 2.3^((temperature- n_b1n_rate_base_q10 )/ n_b1n_rate_TENDEGREES ) ? evaluable
    n_b1n_rate_r = n_b1n_rate_qt  *  n_b1n_rate_rate  * ( n_b1n_rate_factor ^ n_b1n_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=b1n type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_b1n_rr0 = n_b1n_rate_r ? path based, prefix = n_b1n_
    
    n_b1n_rr = n_b1n_rr0 ? evaluable
    n_b1n_rf = 0/ n_b1n_SEC ? evaluable
    n_fi1_rate_qt = 2.3^((temperature- n_fi1_rate_base_q10 )/ n_fi1_rate_TENDEGREES ) ? evaluable
    n_fi1_rate_r = n_fi1_rate_qt  *  n_fi1_rate_rate  * ( n_fi1_rate_factor ^ n_fi1_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=fi1 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_fi1_rf0 = n_fi1_rate_r ? path based, prefix = n_fi1_
    
    n_fi1_rf = n_fi1_rf0 ? evaluable
    n_fi1_rr = 0/ n_fi1_SEC ? evaluable
    n_bi1_rate_qt = 2.3^((temperature- n_bi1_rate_base_q10 )/ n_bi1_rate_TENDEGREES ) ? evaluable
    n_bi1_rate_r = n_bi1_rate_qt  *  n_bi1_rate_rate  * ( n_bi1_rate_factor ^ n_bi1_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=bi1 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_bi1_rr0 = n_bi1_rate_r ? path based, prefix = n_bi1_
    
    n_bi1_rr = n_bi1_rr0 ? evaluable
    n_bi1_rf = 0/ n_bi1_SEC ? evaluable
    n_fi2_rate_qt = 2.3^((temperature- n_fi2_rate_base_q10 )/ n_fi2_rate_TENDEGREES ) ? evaluable
    n_fi2_rate_r = n_fi2_rate_qt  *  n_fi2_rate_rate  * ( n_fi2_rate_factor ^ n_fi2_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=fi2 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_fi2_rf0 = n_fi2_rate_r ? path based, prefix = n_fi2_
    
    n_fi2_rf = n_fi2_rf0 ? evaluable
    n_fi2_rr = 0/ n_fi2_SEC ? evaluable
    n_bi2_rate_qt = 2.3^((temperature- n_bi2_rate_base_q10 )/ n_bi2_rate_TENDEGREES ) ? evaluable
    n_bi2_rate_r = n_bi2_rate_qt  *  n_bi2_rate_rate  * ( n_bi2_rate_factor ^ n_bi2_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=bi2 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_bi2_rr0 = n_bi2_rate_r ? path based, prefix = n_bi2_
    
    n_bi2_rr = n_bi2_rr0 ? evaluable
    n_bi2_rf = 0/ n_bi2_SEC ? evaluable
    n_fi3_rate_qt = 2.3^((temperature- n_fi3_rate_base_q10 )/ n_fi3_rate_TENDEGREES ) ? evaluable
    n_fi3_rate_r = n_fi3_rate_qt  *  n_fi3_rate_rate  * ( n_fi3_rate_factor ^ n_fi3_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=fi3 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_fi3_rf0 = n_fi3_rate_r ? path based, prefix = n_fi3_
    
    n_fi3_rf = n_fi3_rf0 ? evaluable
    n_fi3_rr = 0/ n_fi3_SEC ? evaluable
    n_bi3_rate_qt = 2.3^((temperature- n_bi3_rate_base_q10 )/ n_bi3_rate_TENDEGREES ) ? evaluable
    n_bi3_rate_r = n_bi3_rate_qt  *  n_bi3_rate_rate  * ( n_bi3_rate_factor ^ n_bi3_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=bi3 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_bi3_rr0 = n_bi3_rate_r ? path based, prefix = n_bi3_
    
    n_bi3_rr = n_bi3_rr0 ? evaluable
    n_bi3_rf = 0/ n_bi3_SEC ? evaluable
    n_fi4_rate_qt = 2.3^((temperature- n_fi4_rate_base_q10 )/ n_fi4_rate_TENDEGREES ) ? evaluable
    n_fi4_rate_r = n_fi4_rate_qt  *  n_fi4_rate_rate  * ( n_fi4_rate_factor ^ n_fi4_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=fi4 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_fi4_rf0 = n_fi4_rate_r ? path based, prefix = n_fi4_
    
    n_fi4_rf = n_fi4_rf0 ? evaluable
    n_fi4_rr = 0/ n_fi4_SEC ? evaluable
    n_bi4_rate_qt = 2.3^((temperature- n_bi4_rate_base_q10 )/ n_bi4_rate_TENDEGREES ) ? evaluable
    n_bi4_rate_r = n_bi4_rate_qt  *  n_bi4_rate_rate  * ( n_bi4_rate_factor ^ n_bi4_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=bi4 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_bi4_rr0 = n_bi4_rate_r ? path based, prefix = n_bi4_
    
    n_bi4_rr = n_bi4_rr0 ? evaluable
    n_bi4_rf = 0/ n_bi4_SEC ? evaluable
    n_fi5_rate_qt = 2.3^((temperature- n_fi5_rate_base_q10 )/ n_fi5_rate_TENDEGREES ) ? evaluable
    n_fi5_rate_r = n_fi5_rate_qt  *  n_fi5_rate_rate  * ( n_fi5_rate_factor ^ n_fi5_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=fi5 type=forwardTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_fi5_rf0 = n_fi5_rate_r ? path based, prefix = n_fi5_
    
    n_fi5_rf = n_fi5_rf0 ? evaluable
    n_fi5_rr = 0/ n_fi5_SEC ? evaluable
    n_bi5_rate_qt = 2.3^((temperature- n_bi5_rate_base_q10 )/ n_bi5_rate_TENDEGREES ) ? evaluable
    n_bi5_rate_r = n_bi5_rate_qt  *  n_bi5_rate_rate  * ( n_bi5_rate_factor ^ n_bi5_rate_power ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=bi5 type=reverseTransition), from rate; Component(id=null type=Generic_NaV_rate2)
    n_bi5_rr0 = n_bi5_rate_r ? path based, prefix = n_bi5_
    
    n_bi5_rr = n_bi5_rr0 ? evaluable
    n_bi5_rf = 0/ n_bi5_SEC ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=n type=gateKS), from q10Settings; null
    ? Path not present in component, using factor: 1
    
    n_rateScale = 1 
    
    ? DerivedVariable is based on path: states[*]/q, on: Component(id=n type=gateKS), from states; Component(id=C1 type=closedState)
    ? add applied to all instances of q in: <states> ([Component(id=C1 type=closedState), Component(id=C2 type=closedState), Component(id=C3 type=closedState), Component(id=C4 type=closedState), Component(id=C5 type=closedState), Component(id=I1 type=closedState), Component(id=I2 type=closedState), Component(id=I3 type=closedState), Component(id=I4 type=closedState), Component(id=I5 type=closedState), Component(id=I6 type=closedState), Component(id=O type=openState)]))
    n_q = n_C1_q + n_C2_q + n_C3_q + n_C4_q + n_C5_q + n_I1_q + n_I2_q + n_I3_q + n_I4_q + n_I5_q + n_I6_q + n_O_q ? path based, prefix = n_
    
    n_fcond = n_q ^ n_instances ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
}

