TITLE Mod file for component: Component(id=IT type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    SUFFIX IT
    USEION ca READ eca WRITE ica VALENCE 2 ? Assuming valence = 2 (Ca ion); TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE s_instances                       : parameter
    
    RANGE s_tau                             : exposure
    
    RANGE s_inf                             : exposure
    
    RANGE s_rateScale                       : exposure
    
    RANGE s_fcond                           : exposure
    
    RANGE s_q                               : exposure
    RANGE s_steadyState_VOLT_SCALE          : parameter
    
    RANGE s_steadyState_x                   : exposure
    RANGE s_timeCourse_tau                  : parameter
    
    RANGE s_timeCourse_t                    : exposure
    RANGE u_instances                       : parameter
    
    RANGE u_tau                             : exposure
    
    RANGE u_inf                             : exposure
    
    RANGE u_rateScale                       : exposure
    
    RANGE u_fcond                           : exposure
    RANGE u_timeCourse_TIME_SCALE           : parameter
    RANGE u_timeCourse_VOLT_SCALE           : parameter
    
    RANGE u_timeCourse_t                    : exposure
    RANGE u_steadyState_VOLT_SCALE          : parameter
    
    RANGE u_steadyState_x                   : exposure
    RANGE u_q10Settings_q10Factor           : parameter
    RANGE u_q10Settings_experimentalTemp    : parameter
    RANGE u_q10Settings_TENDEGREES          : parameter
    
    RANGE u_q10Settings_q10                 : exposure
    RANGE s_steadyState_Vm                  : derived variable
    RANGE u_timeCourse_Vm                   : derived variable
    RANGE u_steadyState_Vm                  : derived variable
    RANGE u_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 0 (uS)
    s_instances = 2 
    s_steadyState_VOLT_SCALE = 1 (mV)
    s_timeCourse_tau = 0 (ms)
    u_instances = 1 
    u_timeCourse_TIME_SCALE = 1 (ms)
    u_timeCourse_VOLT_SCALE = 1 (mV)
    u_steadyState_VOLT_SCALE = 1 (mV)
    u_q10Settings_q10Factor = 3 
    u_q10Settings_experimentalTemp = 297.15 (K)
    u_q10Settings_TENDEGREES = 10 (K)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    eca (mV)
    ica (mA/cm2)
    
    
    s_steadyState_Vm                       : derived variable
    
    s_steadyState_x                        : derived variable
    
    s_timeCourse_t (ms)                    : derived variable
    
    s_inf                                  : derived variable
    
    s_fcond                                : derived variable
    
    s_q                                    : derived variable
    
    s_tau                                  : derived variable
    
    s_rateScale                            : derived variable
    
    u_timeCourse_Vm                        : derived variable
    
    u_timeCourse_t (ms)                    : derived variable
    
    u_steadyState_Vm                       : derived variable
    
    u_steadyState_x                        : derived variable
    
    u_q10Settings_q10                      : derived variable
    
    u_rateScale                            : derived variable
    
    u_fcond                                : derived variable
    
    u_inf                                  : derived variable
    
    u_tauUnscaled (ms)                     : derived variable
    
    u_tau (ms)                             : derived variable
    
    conductanceScale                       : derived variable
    
    fopen0                                 : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    rate_u_q (/ms)
    
}

STATE {
    u_q  
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    u_q = u_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=IT type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=IT type=ionChannelHH), from gates; Component(id=s type=IT_s_gate)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=s type=IT_s_gate), Component(id=u type=gateHHtauInf)]))
    fopen0 = s_fcond * u_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ica = gion * (v - eca)
    
}

DERIVATIVE states {
    rates()
    u_q' = rate_u_q 
    
}

PROCEDURE rates() {
    
    s_steadyState_Vm = (v /  s_steadyState_VOLT_SCALE ) ? evaluable
    s_steadyState_x = 1.0 / ( 1 + exp(-( s_steadyState_Vm  + 2 +57)/6.2) ) ? evaluable
    s_timeCourse_t = s_timeCourse_tau ? evaluable
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=s type=IT_s_gate), from steadyState; Component(id=null type=IT_s_inf_inf)
    s_inf = s_steadyState_x ? path based, prefix = s_
    
    s_fcond = s_inf ^ s_instances ? evaluable
    s_q = s_inf ? evaluable
    s_tau = 0 ? evaluable
    s_rateScale = 1 ? evaluable
    u_timeCourse_Vm = (v /  u_timeCourse_VOLT_SCALE )+2 ? evaluable
    u_timeCourse_t = (30.8 + (211.4 + exp(( u_timeCourse_Vm +113.2)/5)) / (1 + exp(( u_timeCourse_Vm +84)/3.2))) *  u_timeCourse_TIME_SCALE ? evaluable
    u_steadyState_Vm = (v /  u_steadyState_VOLT_SCALE ) ? evaluable
    u_steadyState_x = 1.0 / ( 1 + exp(( u_steadyState_Vm  + 2  + 81)/4.0) ) ? evaluable
    u_q10Settings_q10 = u_q10Settings_q10Factor ^((temperature -  u_q10Settings_experimentalTemp )/ u_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=u type=gateHHtauInf), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    u_rateScale = u_q10Settings_q10 ? path based, prefix = u_
    
    u_fcond = u_q ^ u_instances ? evaluable
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=u type=gateHHtauInf), from steadyState; Component(id=null type=IT_u_inf_inf)
    u_inf = u_steadyState_x ? path based, prefix = u_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=u type=gateHHtauInf), from timeCourse; Component(id=null type=IT_u_tau_tau)
    u_tauUnscaled = u_timeCourse_t ? path based, prefix = u_
    
    u_tau = u_tauUnscaled  /  u_rateScale ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    rate_u_q = ( u_inf  -  u_q ) /  u_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
}

