TITLE Mod file for component: Component(id=PVBC type=izhikevichFergusonCell)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    POINT_PROCESS PVBC
    
    
    NONSPECIFIC_CURRENT i                    : To ensure v of section follows v_I
    RANGE v0                                : parameter
    RANGE vr                                : parameter
    RANGE vpeak                             : parameter
    RANGE vt                                : parameter
    RANGE c                                 : parameter
    RANGE klow                              : parameter
    RANGE khigh                             : parameter
    RANGE a                                 : parameter
    RANGE b                                 : parameter
    RANGE d                                 : parameter
    RANGE C                                 : parameter
    
    RANGE k                                 : exposure
    
    RANGE iSyn                              : exposure
    
    RANGE iMemb                             : exposure
    
    RANGE copy_v                           : copy of v on section
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    v0 = -65 (mV)
    vr = -60.6 (mV)
    vpeak = 2.5 (mV)
    vt = -43.1 (mV)
    c = -70 (mV)
    klow = 0.0017 (uS / mV)
    khigh = 0.014 (uS / mV)
    a = 0.1 (kHz)
    b = -1.0E-4 (uS)
    d = 1.0E-4 (nA)
    C = 9.0E-5 (microfarads)
}

ASSIGNED {
    v (mV)
    i (mA/cm2)
    
    copy_v (mV)
    
    v_I (nA) 
    
    iSyn (nA)                              : derived variable
    
    k (uS / mV)                            : conditional derived var...
    rate_v (mV/ms)
    rate_u (nA/ms)
    
}

STATE {
    u (nA) 
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
    net_send(0, 1) : go to NET_RECEIVE block, flag 1, for initial state
    
    u = 0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
    copy_v = v
    i = v_I * C
}

NET_RECEIVE(flag) {
    
    if (flag == 1) { : Setting watch for top level OnCondition...
        WATCH (v >  vpeak) 1000
    }
    if (flag == 1000) {
    
        v = c
    
        v_I = 0 : Setting rate of change of v to 0
    
        u = u  +  d
    }
    if (flag == 1) { : Set initial states
    
        v = v0
    }
    
}

DERIVATIVE states {
    rates()
    u' = rate_u 
    
}

PROCEDURE rates() {
    
    ? DerivedVariable is based on path: synapses[*]/i, on: Component(id=PVBC type=izhikevichFergusonCell), from synapses; null
    iSyn = 0 ? Was: synapses[*]_i but insertion of currents from external attachments not yet supported ? path based, prefix = 
    
    if (v <  vt)  { 
        k = klow ? evaluable cdv
    } else  { 
        k = khigh ? evaluable cdv
    }
    
    rate_v = (  k   * (v-  vr  ) * (v-  vt  ) +  iSyn  -   u  ) /  C ? Note units of all quantities used here need to be consistent!
    rate_u = a  * (  b   * (v-  vr  ) -   u  ) ? Note units of all quantities used here need to be consistent!
    
    v_I = -1 * rate_v
     
    
}

