PREFIX property:<http://neurolex.org/wiki/Property-3A>
PREFIX name:<http://neurolex.org/wiki/Category-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?target ?keyword ?id ?forward ?backward # Last two are stored in "relationship"
WHERE
{
  VALUES ?ids
  {
    [NeuroLexUris]
  }

  ?keyword property:Id ?ids .

  # Find relationships in both directions
  {
    ?target (property:Located_in | property:Neurotransmitter) ?keyword.
    ?target ?forward ?keyword.
  }
  UNION
  {
    ?keyword (property:Located_in | property:Neurotransmitter) ?target.
    ?keyword ?backward ?target.
  }

  ?target property:Id ?id.
}
ORDER BY ?id