TITLE Mod file for component: Component(id=Golgi_hcn1s type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    SUFFIX Golgi_hcn1s
    USEION h READ eh WRITE ih VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE s_instances                       : parameter
    
    RANGE s_tau                             : exposure
    
    RANGE s_inf                             : exposure
    
    RANGE s_rateScale                       : exposure
    
    RANGE s_fcond                           : exposure
    RANGE s_timeCourse_TIME_SCALE           : parameter
    RANGE s_timeCourse_VOLT_SCALE           : parameter
    
    RANGE s_timeCourse_t                    : exposure
    RANGE s_steadyState_TIME_SCALE          : parameter
    RANGE s_steadyState_VOLT_SCALE          : parameter
    
    RANGE s_steadyState_x                   : exposure
    RANGE s_timeCourse_V                    : derived variable
    RANGE s_steadyState_V                   : derived variable
    RANGE s_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)
    s_instances = 1 
    s_timeCourse_TIME_SCALE = 1 (ms)
    s_timeCourse_VOLT_SCALE = 1 (mV)
    s_steadyState_TIME_SCALE = 1 (ms)
    s_steadyState_VOLT_SCALE = 1 (mV)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    eh (mV)
    ih (mA/cm2)
    
    
    s_timeCourse_V                         : derived variable
    
    s_timeCourse_t (ms)                    : derived variable
    
    s_steadyState_V                        : derived variable
    
    s_steadyState_x                        : derived variable
    
    s_rateScale                            : derived variable
    
    s_fcond                                : derived variable
    
    s_inf                                  : derived variable
    
    s_tauUnscaled (ms)                     : derived variable
    
    s_tau (ms)                             : derived variable
    
    conductanceScale                       : derived variable
    
    fopen0                                 : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    rate_s_q (/ms)
    
}

STATE {
    s_q  
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    s_q = s_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=Golgi_hcn1s type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=Golgi_hcn1s type=ionChannelHH), from gates; Component(id=s type=gateHHtauInf)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=s type=gateHHtauInf)]))
    fopen0 = s_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ih = gion * (v - eh)
    
}

DERIVATIVE states {
    rates()
    s_q' = rate_s_q 
    
}

PROCEDURE rates() {
    
    s_timeCourse_V = v /  s_timeCourse_VOLT_SCALE ? evaluable
    s_timeCourse_t = ((exp (((0.01451 *  s_timeCourse_V ) + 4.056 )* 2.302585092 ))) *  s_timeCourse_TIME_SCALE ? evaluable
    s_steadyState_V = v /  s_steadyState_VOLT_SCALE ? evaluable
    s_steadyState_x = (1-(0.002096 *  s_steadyState_V  + 0.97596))  * 1 / (1 + (exp (( s_steadyState_V  - (-72.49)) * 0.11305))) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=s type=gateHHtauInf), from q10Settings; null
    ? Path not present in component, using factor: 1
    
    s_rateScale = 1 
    
    s_fcond = s_q ^ s_instances ? evaluable
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=s type=gateHHtauInf), from steadyState; Component(id=null type=Golgi_hcn1s_s_inf_inf)
    s_inf = s_steadyState_x ? path based, prefix = s_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=s type=gateHHtauInf), from timeCourse; Component(id=null type=Golgi_hcn1s_s_tau_tau)
    s_tauUnscaled = s_timeCourse_t ? path based, prefix = s_
    
    s_tau = s_tauUnscaled  /  s_rateScale ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    rate_s_q = ( s_inf  -  s_q ) /  s_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
}

