TITLE Mod file for component: Component(id=kdrmt type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    SUFFIX kdrmt
    USEION k WRITE ik VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE m_instances                       : parameter
    
    RANGE m_alpha                           : exposure
    
    RANGE m_beta                            : exposure
    
    RANGE m_tau                             : exposure
    
    RANGE m_inf                             : exposure
    
    RANGE m_rateScale                       : exposure
    
    RANGE m_fcond                           : exposure
    RANGE m_forwardRate_TIME_SCALE          : parameter
    RANGE m_forwardRate_VOLT_SCALE          : parameter
    RANGE m_forwardRate_zetam               : parameter
    RANGE m_forwardRate_vhalfm              : parameter
    RANGE m_forwardRate_gmm                 : parameter
    RANGE m_forwardRate_a0m                 : parameter
    
    RANGE m_forwardRate_r                   : exposure
    RANGE m_reverseRate_TIME_SCALE          : parameter
    RANGE m_reverseRate_VOLT_SCALE          : parameter
    RANGE m_reverseRate_zetam               : parameter
    RANGE m_reverseRate_vhalfm              : parameter
    RANGE m_reverseRate_gmm                 : parameter
    RANGE m_reverseRate_a0m                 : parameter
    
    RANGE m_reverseRate_r                   : exposure
    RANGE m_timeCourse_TIME_SCALE           : parameter
    RANGE m_timeCourse_VOLT_SCALE           : parameter
    RANGE m_timeCourse_zetam                : parameter
    RANGE m_timeCourse_vhalfm               : parameter
    RANGE m_timeCourse_gmm                  : parameter
    RANGE m_timeCourse_a0m                  : parameter
    
    RANGE m_timeCourse_t                    : exposure
    RANGE m_steadyState_TIME_SCALE          : parameter
    RANGE m_steadyState_VOLT_SCALE          : parameter
    RANGE m_steadyState_zetam               : parameter
    RANGE m_steadyState_vhalfm              : parameter
    RANGE m_steadyState_gmm                 : parameter
    RANGE m_steadyState_a0m                 : parameter
    
    RANGE m_steadyState_x                   : exposure
    RANGE m_q10Settings_q10Factor           : parameter
    RANGE m_q10Settings_experimentalTemp    : parameter
    RANGE m_q10Settings_TENDEGREES          : parameter
    
    RANGE m_q10Settings_q10                 : exposure
    RANGE m_forwardRate_V                   : derived variable
    RANGE m_forwardRate_Vhalfm              : derived variable
    RANGE m_reverseRate_V                   : derived variable
    RANGE m_reverseRate_Vhalfm              : derived variable
    RANGE m_timeCourse_V                    : derived variable
    RANGE m_timeCourse_Vhalfm               : derived variable
    RANGE m_timeCourse_ALPHA                : derived variable
    RANGE m_timeCourse_BETA                 : derived variable
    RANGE m_steadyState_V                   : derived variable
    RANGE m_steadyState_Vhalfm              : derived variable
    RANGE m_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)
    m_instances = 1 
    m_forwardRate_TIME_SCALE = 1 (ms)
    m_forwardRate_VOLT_SCALE = 1 (mV)
    m_forwardRate_zetam = 0.055 
    m_forwardRate_vhalfm = -50 
    m_forwardRate_gmm = 0.5 
    m_forwardRate_a0m = 0.0035 
    m_reverseRate_TIME_SCALE = 1 (ms)
    m_reverseRate_VOLT_SCALE = 1 (mV)
    m_reverseRate_zetam = 0.055 
    m_reverseRate_vhalfm = -50 
    m_reverseRate_gmm = 0.5 
    m_reverseRate_a0m = 0.0035 
    m_timeCourse_TIME_SCALE = 1 (ms)
    m_timeCourse_VOLT_SCALE = 1 (mV)
    m_timeCourse_zetam = 0.055 
    m_timeCourse_vhalfm = -50 
    m_timeCourse_gmm = 0.5 
    m_timeCourse_a0m = 0.0035 
    m_steadyState_TIME_SCALE = 1 (ms)
    m_steadyState_VOLT_SCALE = 1 (mV)
    m_steadyState_zetam = 0.055 
    m_steadyState_vhalfm = -50 
    m_steadyState_gmm = 0.5 
    m_steadyState_a0m = 0.0035 
    m_q10Settings_q10Factor = 3 
    m_q10Settings_experimentalTemp = 297.15 (K)
    m_q10Settings_TENDEGREES = 10 (K)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ek (mV)
    ik (mA/cm2)
    
    
    m_forwardRate_V                        : derived variable
    
    m_forwardRate_Vhalfm                   : derived variable
    
    m_forwardRate_r (kHz)                  : derived variable
    
    m_reverseRate_V                        : derived variable
    
    m_reverseRate_Vhalfm                   : derived variable
    
    m_reverseRate_r (kHz)                  : derived variable
    
    m_timeCourse_V                         : derived variable
    
    m_timeCourse_Vhalfm                    : derived variable
    
    m_timeCourse_ALPHA                     : derived variable
    
    m_timeCourse_BETA                      : derived variable
    
    m_timeCourse_t (ms)                    : derived variable
    
    m_steadyState_V                        : derived variable
    
    m_steadyState_Vhalfm                   : derived variable
    
    m_steadyState_x                        : derived variable
    
    m_q10Settings_q10                      : derived variable
    
    m_rateScale                            : derived variable
    
    m_alpha (kHz)                          : derived variable
    
    m_beta (kHz)                           : derived variable
    
    m_inf                                  : derived variable
    
    m_tauUnscaled (ms)                     : derived variable
    
    m_tau (ms)                             : derived variable
    
    m_fcond                                : derived variable
    
    conductanceScale                       : derived variable
    
    fopen0                                 : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    rate_m_q (/ms)
    
}

STATE {
    m_q  
    
}

INITIAL {
    ek = -90.0
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    m_q = m_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=kdrmt type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=kdrmt type=ionChannelHH), from gates; Component(id=m type=gateHHratesTauInf)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=m type=gateHHratesTauInf)]))
    fopen0 = m_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ik = gion * (v - ek)
    
}

DERIVATIVE states {
    rates()
    m_q' = rate_m_q 
    
}

PROCEDURE rates() {
    
    m_forwardRate_V = v /  m_forwardRate_VOLT_SCALE ? evaluable
    m_forwardRate_Vhalfm = m_forwardRate_vhalfm ? evaluable
    m_forwardRate_r = ((exp (  m_forwardRate_zetam  * ( m_forwardRate_V  -  m_forwardRate_Vhalfm )) )) /  m_forwardRate_TIME_SCALE ? evaluable
    m_reverseRate_V = v /  m_reverseRate_VOLT_SCALE ? evaluable
    m_reverseRate_Vhalfm = m_reverseRate_vhalfm ? evaluable
    m_reverseRate_r = ((exp (  m_reverseRate_zetam  *  m_reverseRate_gmm  * ( m_reverseRate_V  -  m_reverseRate_Vhalfm )) )) /  m_reverseRate_TIME_SCALE ? evaluable
    m_timeCourse_V = v /  m_timeCourse_VOLT_SCALE ? evaluable
    m_timeCourse_Vhalfm = m_timeCourse_vhalfm ? evaluable
    m_timeCourse_ALPHA = m_alpha  *  m_timeCourse_TIME_SCALE ? evaluable
    m_timeCourse_BETA = m_beta  *  m_timeCourse_TIME_SCALE ? evaluable
    m_timeCourse_t = ( m_timeCourse_BETA  / (  m_timeCourse_a0m  * (1 +  m_timeCourse_ALPHA ))) *  m_timeCourse_TIME_SCALE ? evaluable
    m_steadyState_V = v /  m_steadyState_VOLT_SCALE ? evaluable
    m_steadyState_Vhalfm = m_steadyState_vhalfm ? evaluable
    m_steadyState_x = 1/(1 + (exp ( ( m_steadyState_V  - 21) /(-10) ))) ? evaluable
    m_q10Settings_q10 = m_q10Settings_q10Factor ^((temperature -  m_q10Settings_experimentalTemp )/ m_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=m type=gateHHratesTauInf), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    m_rateScale = m_q10Settings_q10 ? path based, prefix = m_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=m type=gateHHratesTauInf), from forwardRate; Component(id=null type=kdrmt_m_alpha_rate)
    m_alpha = m_forwardRate_r ? path based, prefix = m_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=m type=gateHHratesTauInf), from reverseRate; Component(id=null type=kdrmt_m_beta_rate)
    m_beta = m_reverseRate_r ? path based, prefix = m_
    
    ? DerivedVariable is based on path: steadyState/x, on: Component(id=m type=gateHHratesTauInf), from steadyState; Component(id=null type=kdrmt_m_inf_inf)
    m_inf = m_steadyState_x ? path based, prefix = m_
    
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=m type=gateHHratesTauInf), from timeCourse; Component(id=null type=kdrmt_m_tau_tau)
    m_tauUnscaled = m_timeCourse_t ? path based, prefix = m_
    
    m_tau = m_tauUnscaled  /  m_rateScale ? evaluable
    m_fcond = m_q ^ m_instances ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    rate_m_q = ( m_inf  -  m_q ) /  m_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    
     
    
}

