TITLE Mod file for component: Component(id=FN type=fitzHughNagumo1969Cell)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    POINT_PROCESS FN
    RANGE a                                 : parameter
    RANGE b                                 : parameter
    RANGE I                                 : parameter
    RANGE phi                               : parameter
    RANGE V0                                : parameter
    RANGE W0                                : parameter
    RANGE TS                                : parameter
    
    RANGE F                                 : exposure
    
    RANGE copy_v                           : copy of v on section
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    a = 0.7 
    b = 0.08 
    I = 1 
    phi = 0.08 
    V0 = 0 
    W0 = 0 
    TS = 1 (ms)
}

ASSIGNED {
    
    F                                      : derived variable
    rate_V (/ms)
    rate_W (/ms)
    
}

STATE {
    V  
    W  
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
    V = V0
    
    W = W0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
}

DERIVATIVE states {
    rates()
    V' = rate_V 
    W' = rate_W 
    
}

PROCEDURE rates() {
    
    F = V  -   V  ^3 / 3 ? evaluable
    rate_V = (  F   -  W  +   I  ) /  TS ? Note units of all quantities used here need to be consistent!
    rate_W = phi  * (  V   +  a  -  b  *   W  ) /  TS ? Note units of all quantities used here need to be consistent!
    
     
    
}

