TITLE Mod file for component: Component(id=GLIF_480633674 type=glifRCell)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.3
         org.neuroml.model   v1.5.3
         jLEMS               v0.9.9.0

ENDCOMMENT

NEURON {
    POINT_PROCESS GLIF_480633674
    
    
    NONSPECIFIC_CURRENT i                    : To ensure v of section follows v_I
    RANGE leakConductance                   : parameter
    RANGE leakReversal                      : parameter
    RANGE bs                                : parameter
    RANGE deltaThresh                       : parameter
    RANGE deltaV                            : parameter
    RANGE fv                                : parameter
    RANGE thresh                            : parameter
    RANGE reset                             : parameter
    RANGE C                                 : parameter
    
    RANGE threshTotal                       : exposure
    
    RANGE iSyn                              : exposure
    
    RANGE iMemb                             : exposure
    
    RANGE copy_v                           : copy of v on section
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    leakConductance = 0.003819812 (uS)
    leakReversal = 0 (mV)
    bs = 0.14598246 (kHz)
    deltaThresh = 1.9547837 (mV)
    deltaV = 9.518427 (mV)
    fv = 0.045714617 
    thresh = 23.832537 (mV)
    reset = 0 (mV)
    C = 5.373192E-5 (microfarads)
}

ASSIGNED {
    v (mV)
    i (mA/cm2)
    
    copy_v (mV)
    
    v_I (nA) 
    
    iSyn (nA)                              : derived variable
    
    iMemb (nA)                             : derived variable
    
    threshTotal (mV)                       : derived variable
    rate_v (mV/ms)
    rate_threshS (mV/ms)
    
}

STATE {
    threshS (mV) 
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
    net_send(0, 1) : go to NET_RECEIVE block, flag 1, for initial state
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
    copy_v = v
    i = v_I * C
}

NET_RECEIVE(flag) {
    
    if (flag == 1) { : Setting watch for top level OnCondition...
        WATCH (v >  threshTotal) 1000
    }
    if (flag == 1000) {
    
        v = leakReversal  +  fv  * (v -   leakReversal  ) +  deltaV
    
        v_I = 0 : Setting rate of change of v to 0
    
        threshS = threshS  +  deltaThresh
    }
    if (flag == 1) { : Set initial states
    
        v = leakReversal
    }
    
}

DERIVATIVE states {
    rates()
    threshS' = rate_threshS 
    
}

PROCEDURE rates() {
    
    ? DerivedVariable is based on path: synapses[*]/i, on: Component(id=GLIF_480633674 type=glifRCell), from synapses; null
    iSyn = 0 ? Was: synapses[*]_i but insertion of currents from external attachments not yet supported ? path based, prefix = 
    
    iMemb = leakConductance  * (  leakReversal   - v)  +  iSyn ? evaluable
    threshTotal = thresh  +  threshS ? evaluable
    rate_v = iMemb  /  C ? Note units of all quantities used here need to be consistent!
    rate_threshS = -1 *  bs  *  threshS ? Note units of all quantities used here need to be consistent!
    
    v_I = -1 * rate_v
     
    
}

